//ACTION TYPES

//authReducer
export const SET_LOAD_DATA = "SET_LOAD_DATA"
export const ADD_DATA = "ADD_DATA"
export const ADD_MODIFIED_DATA = "ADD_MODIFIED_DATA"
export const ADD_RENDERED_CUSTOM_DATA = "ADD_RENDERED_CUSTOM_DATA"
export const ADD_RENDERED_DATA = "ADD_RENDERED_DATA"